# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source :gemcutter

gem "ruby-xslt", ">=0.9.9"
gem "ruby-graphviz", ">=1.0.8"

gem "rdoc", "~>3.10", :group => [:development, :test]
gem "newgem", ">=1.5.3", :group => [:development, :test]
gem "hoe", "~>3.0", :group => [:development, :test]

# vim: syntax=ruby
